name: Build Linux app

on:
  push:
    branches: main

jobs:
  build:
    name: Build Linux app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tarok
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
      - name: Install build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libsecret-1-dev libjsoncpp-dev
      - name: Get dependencies
        run: flutter pub upgrade
      - name: Enable Linux desktop for building
        run: flutter config --enable-linux-desktop
      - name: Run flutter doctor for inspection
        run: flutter doctor -v
      - name: Run flutter devices for getting all devices info
        run: flutter devices
      - name: Build Linux app
        run: flutter build linux --verbose
      - run: ls build/linux/x64/release/bundle
      - uses: actions/upload-artifact@v3
        with:
          name: linux_app
          path: build/linux/x64/release/bundle
