name: Build web app

on:
  push:
    branches: main

jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tarok
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
      - run: flutter pub upgrade
      - run: flutter build apk --verbose
      - uses: actions/upload-artifact@v3
        with:
          name: android_app
          path: build/app/outputs/apk/release/app-release.apk
  build-windows:
    name: Build .exe for Windows
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./tarok
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
      - run: flutter pub upgrade
      - run: flutter pub get
      - run: flutter config --enable-windows-desktop
      - run: flutter doctor --verbose
      - run: flutter devices
      - run: flutter build windows --verbose
      - uses: actions/upload-artifact@v3
        with:
          name: windows_app
          path: build\windows\runner\Release\
  build-linux:
    name: Build Linux app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tarok
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
      - name: Install build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libsecret-1-dev libjsoncpp-dev
      - name: Get dependencies
        run: flutter pub upgrade
      - name: Enable Linux desktop for building
        run: flutter config --enable-linux-desktop
      - name: Run flutter doctor for inspection
        run: flutter doctor -v
      - name: Run flutter devices for getting all devices info
        run: flutter devices
      - name: Build Linux app
        run: flutter build linux --verbose
      - run: ls build/linux/x64/release/bundle
      - uses: actions/upload-artifact@v3
        with:
          name: linux_app
          path: build/linux/x64/release/bundle
  build-web:
    name: Build web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tarok
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
      - run: flutter pub upgrade
      - run: flutter build web --verbose
      - uses: actions/upload-artifact@v3
        with:
          name: web_app
          path: tarok/build/web
